name: build bridge-www
on:
  push:
    paths:
    - bridge-www/**/*

  pull_request:
    paths:
    - bridge-www/**/*

jobs:
  build-bridge-www:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: bridge-www/yarn.lock
      - run: yarn
        working-directory: ./bridge-www
      - run: |
          cp package.json /tmp/package.json
          jq --arg repository "$REPOSITORY" '.homepage = ($repository | split("/") | "https://\(.[0]).github.io/\(.[1])")' < /tmp/package.json > package.json
          yarn build
        working-directory: ./bridge-www
        env:
          REPOSITORY: ${{ github.repository }}
      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./bridge-www/build
